service: minemanager

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:*"
      Resource: "*"
  environment:
    TOKEN: "sometokenhere"

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  manager:
    handler: bin/manager
    memorySize: 128
    events:
      - httpApi:
          path: /start
          method: post
      - httpApi:
          path: /stop
          method: post
      - httpApi:
          path: /ip
          method: get
